### ISSUE TITLE
TypeError - line 96

### ISSUE THREAD

**Issue by majidmc2** [kytos/of_l2ls#34]
I want to use Kytos with Mininet based on this [document](https://tutorials.kytos.io/napps/how_to_use_kytos_with_mininet/). I get this error when I try to **Ping**.

- mininet:
```
> h1 ping h2
```

- kytosd logs:
```
Exception in thread Thread-105:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/kytos-2021.1-py3.8.egg/kytos/core/helpers.py", line 70, in threaded_handler
    handler(*args)
  File "//var/lib/kytos/napps/kytos/of_l2ls/main.py", line 161, in handle_packet_in
    packet_out = self._create_packet_out(version, packet_in, ports, switch)
  File "//var/lib/kytos/napps/kytos/of_l2ls/main.py", line 96, in _create_packet_out
    if iface and (iface.config & PortConfig10.OFPPC_NO_FWD ==
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'

```

**Comment by josemauro** [comment]
You should try **kytos-ng** (https://github.com/kytos-ng/kytos), a fork from the original Kytos SDN Project (https://github.com/kytos/). Check it out, if you get the same error using **kytos-ng** and reopen this issue there.

**Comment by viniarck** [comment]
@majidmc2, **kytos-ng** tutorials docs is still in progress, however the page that documents [how to setup the environment](https://github.com/kytos-ng/documentation/blob/master/tutorials/napps/development_environment_setup.rst) is updated, Python 3.9 is the current supported main version now, also OpenFlow 1.0 will be deprecated, `of_l2ls` works with OpenFlow1.3. The rest of the tutorial docs will likely be updated soon. In the meantime, if you need help [you can also join kytos-ng Slack workspace](https://join.slack.com/t/kytos-ng/shared_invite/zt-19yqld4n7-QrjIUPV4I1bPUBkIcayamA). 

@josemauro, appreciated your help :)
